[phases.setup]
nixPkgs = ["tesseract", "tessdata", "libGL", "glib"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python main.py"

[variables]
NIXPACKS_PYTHON_VERSION = "3.12"
